// AUTO-GENERATED by scripts/process-images.mjs. Do not edit by hand.
// Run "npm run images" to regenerate after adding or changing photos.

export type GalleryImage = { full: string; thumb: string; w: number; h: number };
export type GalleryEntry = { cover: string | null; images: GalleryImage[] };

export const galleries: Record<string, GalleryEntry> = {
  "amd-gameon": {
    cover: "/images/work/amd-gameon/cover.webp",
    images: [
      { full: "/images/work/amd-gameon/cover-full.webp", thumb: "/images/work/amd-gameon/cover-thumb.webp", w: 1600, h: 713 },
      { full: "/images/work/amd-gameon/1-full.webp", thumb: "/images/work/amd-gameon/1-thumb.webp", w: 1600, h: 902 },
      { full: "/images/work/amd-gameon/2-full.webp", thumb: "/images/work/amd-gameon/2-thumb.webp", w: 1600, h: 907 },
      { full: "/images/work/amd-gameon/3-full.webp", thumb: "/images/work/amd-gameon/3-thumb.webp", w: 1600, h: 905 },
      { full: "/images/work/amd-gameon/4-full.webp", thumb: "/images/work/amd-gameon/4-thumb.webp", w: 1600, h: 902 },
      { full: "/images/work/amd-gameon/5-full.webp", thumb: "/images/work/amd-gameon/5-thumb.webp", w: 1600, h: 903 },
    ],
  },
  "college-rivals": {
    cover: "/images/work/college-rivals/cover.webp",
    images: [
      { full: "/images/work/college-rivals/cover-full.webp", thumb: "/images/work/college-rivals/cover-thumb.webp", w: 1600, h: 905 },
      { full: "/images/work/college-rivals/1-full.webp", thumb: "/images/work/college-rivals/1-thumb.webp", w: 1232, h: 696 },
      { full: "/images/work/college-rivals/2-full.webp", thumb: "/images/work/college-rivals/2-thumb.webp", w: 552, h: 313 },
      { full: "/images/work/college-rivals/3-full.webp", thumb: "/images/work/college-rivals/3-thumb.webp", w: 687, h: 373 },
      { full: "/images/work/college-rivals/4-full.webp", thumb: "/images/work/college-rivals/4-thumb.webp", w: 680, h: 394 },
      { full: "/images/work/college-rivals/5-full.webp", thumb: "/images/work/college-rivals/5-thumb.webp", w: 680, h: 336 },
      { full: "/images/work/college-rivals/6-full.webp", thumb: "/images/work/college-rivals/6-thumb.webp", w: 1600, h: 905 },
    ],
  },
  "comiccon-bengaluru": {
    cover: "/images/work/comiccon-bengaluru/cover.webp",
    images: [
      { full: "/images/work/comiccon-bengaluru/cover-full.webp", thumb: "/images/work/comiccon-bengaluru/cover-thumb.webp", w: 1080, h: 618 },
      { full: "/images/work/comiccon-bengaluru/1-full.webp", thumb: "/images/work/comiccon-bengaluru/1-thumb.webp", w: 720, h: 1154 },
      { full: "/images/work/comiccon-bengaluru/2-full.webp", thumb: "/images/work/comiccon-bengaluru/2-thumb.webp", w: 720, h: 1280 },
      { full: "/images/work/comiccon-bengaluru/3-full.webp", thumb: "/images/work/comiccon-bengaluru/3-thumb.webp", w: 1080, h: 727 },
    ],
  },
  "comiccon-delhi": {
    cover: "/images/work/comiccon-delhi/cover.webp",
    images: [
      { full: "/images/work/comiccon-delhi/cover-full.webp", thumb: "/images/work/comiccon-delhi/cover-thumb.webp", w: 1600, h: 835 },
      { full: "/images/work/comiccon-delhi/1-full.webp", thumb: "/images/work/comiccon-delhi/1-thumb.webp", w: 1600, h: 2842 },
      { full: "/images/work/comiccon-delhi/2-full.webp", thumb: "/images/work/comiccon-delhi/2-thumb.webp", w: 1600, h: 2842 },
      { full: "/images/work/comiccon-delhi/3-full.webp", thumb: "/images/work/comiccon-delhi/3-thumb.webp", w: 1600, h: 2133 },
      { full: "/images/work/comiccon-delhi/4-full.webp", thumb: "/images/work/comiccon-delhi/4-thumb.webp", w: 1600, h: 2842 },
      { full: "/images/work/comiccon-delhi/5-full.webp", thumb: "/images/work/comiccon-delhi/5-thumb.webp", w: 1600, h: 2842 },
      { full: "/images/work/comiccon-delhi/6-full.webp", thumb: "/images/work/comiccon-delhi/6-thumb.webp", w: 1600, h: 2842 },
    ],
  },
  "freefire-jjk": {
    cover: "/images/work/freefire-jjk/cover.webp",
    images: [
      { full: "/images/work/freefire-jjk/cover-full.webp", thumb: "/images/work/freefire-jjk/cover-thumb.webp", w: 1079, h: 608 },
      { full: "/images/work/freefire-jjk/1-full.webp", thumb: "/images/work/freefire-jjk/1-thumb.webp", w: 1600, h: 2133 },
    ],
  },
  "lenovo-techworld": {
    cover: "/images/work/lenovo-techworld/cover.webp",
    images: [
      { full: "/images/work/lenovo-techworld/cover-full.webp", thumb: "/images/work/lenovo-techworld/cover-thumb.webp", w: 1600, h: 722 },
      { full: "/images/work/lenovo-techworld/1-full.webp", thumb: "/images/work/lenovo-techworld/1-thumb.webp", w: 1600, h: 882 },
      { full: "/images/work/lenovo-techworld/2-full.webp", thumb: "/images/work/lenovo-techworld/2-thumb.webp", w: 1600, h: 882 },
      { full: "/images/work/lenovo-techworld/3-full.webp", thumb: "/images/work/lenovo-techworld/3-thumb.webp", w: 1600, h: 900 },
      { full: "/images/work/lenovo-techworld/4-full.webp", thumb: "/images/work/lenovo-techworld/4-thumb.webp", w: 1600, h: 899 },
      { full: "/images/work/lenovo-techworld/5-full.webp", thumb: "/images/work/lenovo-techworld/5-thumb.webp", w: 1600, h: 900 },
      { full: "/images/work/lenovo-techworld/6-full.webp", thumb: "/images/work/lenovo-techworld/6-thumb.webp", w: 1600, h: 900 },
    ],
  },
  "riot-convergence": {
    cover: "/images/work/riot-convergence/cover.webp",
    images: [
      { full: "/images/work/riot-convergence/cover-full.webp", thumb: "/images/work/riot-convergence/cover-thumb.webp", w: 1600, h: 1067 },
      { full: "/images/work/riot-convergence/1-full.webp", thumb: "/images/work/riot-convergence/1-thumb.webp", w: 1600, h: 1067 },
      { full: "/images/work/riot-convergence/2-full.webp", thumb: "/images/work/riot-convergence/2-thumb.webp", w: 1600, h: 1067 },
      { full: "/images/work/riot-convergence/3-full.webp", thumb: "/images/work/riot-convergence/3-thumb.webp", w: 1600, h: 1143 },
      { full: "/images/work/riot-convergence/4-full.webp", thumb: "/images/work/riot-convergence/4-thumb.webp", w: 1600, h: 1067 },
      { full: "/images/work/riot-convergence/5-full.webp", thumb: "/images/work/riot-convergence/5-thumb.webp", w: 1600, h: 1067 },
      { full: "/images/work/riot-convergence/6-full.webp", thumb: "/images/work/riot-convergence/6-thumb.webp", w: 1600, h: 1067 },
    ],
  },
  "samsung-2024": {
    cover: "/images/work/samsung-2024/cover.webp",
    images: [
      { full: "/images/work/samsung-2024/cover-full.webp", thumb: "/images/work/samsung-2024/cover-thumb.webp", w: 1289, h: 1202 },
      { full: "/images/work/samsung-2024/1-full.webp", thumb: "/images/work/samsung-2024/1-thumb.webp", w: 1289, h: 1289 },
      { full: "/images/work/samsung-2024/2-full.webp", thumb: "/images/work/samsung-2024/2-thumb.webp", w: 1280, h: 720 },
    ],
  },
  "samsung-2025": {
    cover: "/images/work/samsung-2025/cover.webp",
    images: [
      { full: "/images/work/samsung-2025/cover-full.webp", thumb: "/images/work/samsung-2025/cover-thumb.webp", w: 1600, h: 1066 },
      { full: "/images/work/samsung-2025/1-full.webp", thumb: "/images/work/samsung-2025/1-thumb.webp", w: 1600, h: 2133 },
      { full: "/images/work/samsung-2025/2-full.webp", thumb: "/images/work/samsung-2025/2-thumb.webp", w: 1600, h: 2134 },
      { full: "/images/work/samsung-2025/3-full.webp", thumb: "/images/work/samsung-2025/3-thumb.webp", w: 1600, h: 2133 },
      { full: "/images/work/samsung-2025/4-full.webp", thumb: "/images/work/samsung-2025/4-thumb.webp", w: 1600, h: 2133 },
      { full: "/images/work/samsung-2025/5-full.webp", thumb: "/images/work/samsung-2025/5-thumb.webp", w: 1600, h: 2134 },
      { full: "/images/work/samsung-2025/6-full.webp", thumb: "/images/work/samsung-2025/6-thumb.webp", w: 1600, h: 2133 },
    ],
  },
  "waves-summit": {
    cover: "/images/work/waves-summit/cover.webp",
    images: [
      { full: "/images/work/waves-summit/cover-full.webp", thumb: "/images/work/waves-summit/cover-thumb.webp", w: 1280, h: 625 },
      { full: "/images/work/waves-summit/1-full.webp", thumb: "/images/work/waves-summit/1-thumb.webp", w: 1280, h: 960 },
      { full: "/images/work/waves-summit/2-full.webp", thumb: "/images/work/waves-summit/2-thumb.webp", w: 1280, h: 960 },
      { full: "/images/work/waves-summit/3-full.webp", thumb: "/images/work/waves-summit/3-thumb.webp", w: 1280, h: 960 },
      { full: "/images/work/waves-summit/4-full.webp", thumb: "/images/work/waves-summit/4-thumb.webp", w: 1280, h: 960 },
      { full: "/images/work/waves-summit/5-full.webp", thumb: "/images/work/waves-summit/5-thumb.webp", w: 1280, h: 720 },
      { full: "/images/work/waves-summit/6-full.webp", thumb: "/images/work/waves-summit/6-thumb.webp", w: 1280, h: 720 },
    ],
  },
};
